name: Generar gr치ficos de evoluci칩n por canal

on:
  schedule:
    - cron: '30 6 2 * *'   # Segundo d칤a de cada mes a las 6:30 UTC
  workflow_dispatch:       # Tambi칠n se puede ejecutar manualmente

jobs:
  graficos-evolucion:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repositorio
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Instalar dependencias
      run: |
        pip install --upgrade pip
        pip install pandas matplotlib

    - name: Ejecutar script de evoluci칩n
      run: python extractor/evolucion_canales_separado.py

    - name: Hacer commit de los gr치ficos generados
      run: |
        git config --global user.email "bot@example.com"
        git config --global user.name "GitHub Actions Bot"
        git add data/canales/graficos/*.png
        git commit -m "游늵 Gr치ficos de evoluci칩n mensual actualizados" || echo "Nada para commitear"
        git push
