- name: Ejecutar visualizador
        run: |
          python extractor/generar_grafico.py

      - name: Guardar cambios
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add grafico_ecosistema_mendoza.png
          git commit -m "Reporte mensual automático" || echo "Sin cambios"
          git push
