# .github/workflows/youtube_report.yml

name: YouTube Report Generator

on:
  schedule:
    - cron: '0 14 * * 1'  # Ejecuta los lunes a las 11 AM Argentina (UTC-3)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r extractor/requirements.txt

      - name: Ejecutar script de análisis mensual
        run: |
          python extractor/generate_post.py

      - name: Subir cambios generados
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add output/
          git commit -m "📊 Reporte mensual generado automáticamente"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

