name: YouTube Monthly Report

on:
  schedule:
    - cron: '0 2 1 * *'
  workflow_dispatch:

jobs:
  generate-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r extractor/requirements.txt

      - name: Set up YOUTUBE_API_KEY
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        run: echo "YOUTUBE_API_KEY=${YOUTUBE_API_KEY}" > extractor/.env

      - name: Run YouTube Report Script
        run: python extractor/youtube_report.py

      - name: Get current year and month
        id: date
        run: echo "month=$(date +'%Y%m')" >> $GITHUB_OUTPUT

      - name: Commit and push report
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add data/report_${{ steps.date.outputs.month }}.csv
          git commit -m "Automated monthly report [skip ci]" || echo "No changes to commit"
          git push
